tosca_definitions_version: cloudify_dsl_1_3

description: test description

inputs:

  input1:
    type: string
    description: test input
    default: 'test'

node_types:

  node_type1:
    derived_from: cloudify.nodes.Root
    properties:
      prop1:
        type: string
        description: >
          test prop
        default: { get_input: input1 }
